#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("android2.Resource", IsApplication=true)]

namespace android2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::android2.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::android2.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::android2.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apple = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int banana = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int beef = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buckwheat = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cheesecurdsnack = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int chicken = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cucumber = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int curd = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int egg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int loafofbread = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int orange = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pastapng = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pear = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int pizzapng = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pork = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int potato = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int slicewatermelon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int souppng = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int tomato = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int turkey = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int alerttext1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int alerttext2 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int alerttext3 = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int caloriestxt = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int clearbutton = 2131099671;
			
			// aapt resource value: 0x7f06000a
			public const int clearfinalbutton = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int contentFrame = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int dailyviewbutton = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int emptydayview = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int emptyfoodlog = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int emptymyfoodsview = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int gridbutton = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int gridview = 2131099672;
			
			// aapt resource value: 0x7f060006
			public const int inputgram = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int inputnewcal = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int inputnewfood = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int listdays = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int listfoodlog = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int listviewmyfoods = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int logbutton = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int manualbutton = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int scanbutton = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int searchviewmyfoods = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int textView1 = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int toolbar = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int undolastbutton = 2131099661;
			
			// aapt resource value: 0x7f060019
			public const int viewpager = 2131099673;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateFoodAlert = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DayListPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Gridpage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Listmyfoods = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RealGridpage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Tabpage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int CodeFont = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
